Repository elastic/crawler, pull requests merged in 2024-08, with the labels that each got.

#63 Fix redirect and error crawl result handling
  lib/crawler/coordinator.rb
  lib/crawler/data/crawl_result/base.rb
  lib/crawler/data/rule_engine_outcome.rb
  lib/crawler/rule_engine/base.rb
  spec/integration/legacy_sitemaps_spec.rb
  spec/integration/redirects_spec.rb
  spec/integration/sitemap_xxe_spec.rb
  spec/lib/crawler/coordinator_spec.rb
Labels: v0.2.0

#72 Bump rexml to 3.3.4
  Gemfile.lock
Labels: v0.1.1, v0.2.0, auto-backport

#70 Rename fatal error to internal error
  lib/crawler/data/crawl_result/error.rb
Labels: v0.2.0

#89 main was missing some "make install" diffs
  Jars.lock
  vendor/jars/org/snakeyaml/snakeyaml-engine/2.7/snakeyaml-engine-2.7.jar
Labels: v0.2.0

#91 Pin gems and set some platforms as jruby
  Gemfile
  Gemfile.lock
  NOTICE.txt
  script/licenses/lib/third_party/rubygems_dependencies.rb
  script/licenses/rubygems_licenses/_manually_added_strscan-LICENSE.txt
Labels: v0.2.0

#97 Update renovate to only consider chainguard
  renovate.json
Labels: v0.2.0

#90 update webmock
  Gemfile
  Gemfile.lock
  NOTICE.txt
Labels: v0.2.0

#74 Add binary content extraction
  lib/crawler/data/crawl_result/content_extractable_file.rb
  lib/crawler/document_mapper.rb
  lib/crawler/http_executor.rb
  lib/crawler/http_utils/response.rb
  lib/crawler/output_sink/base.rb
  lib/crawler/output_sink/elasticsearch.rb
  spec/factories/crawl_results.rb
  spec/lib/crawler/document_mapper_spec.rb
  spec/lib/crawler/output_sink/elasticsearch_spec.rb
Labels: v0.2.0, release_note

#104 Update catalog-info.yaml for docker publishing
  .buildkite/release-pipeline.yml
  catalog-info.yaml
Labels: v0.1.1, v0.2.0, auto-backport

#107 [0.1] Update catalog-info.yaml for docker publishing (#104)
  .buildkite/release-pipeline.yml
  catalog-info.yaml
Labels: backport

#106 Add Dockerfile.wolfi
  Dockerfile.wolfi
Labels: v0.1.1, v0.2.0, auto-backport

#112 Add scheduling CLI command
  Gemfile
  Gemfile.lock
  NOTICE.txt
  README.md
  config/crawler.yml.example
  docs/features/SCHEDULING.md
  lib/crawler/api/config.rb
  lib/crawler/cli.rb
  lib/crawler/cli/schedule.rb
  spec/fixtures/crawl.yml
  spec/lib/crawler/cli/schedule_spec.rb
Labels: v0.2.0, release_note

#113 Add documentation for binary content extraction and ingest pipelines
  config/crawler.yml.example
  docs/features/BINARY_CONTENT_EXTRACTION.md
  docs/features/INGEST_PIPELINES.md
  lib/crawler/api/config.rb
  lib/crawler/http_executor.rb
  spec/lib/crawler/http_executor_spec.rb
  spec/support/faux/faux_crawl.rb
Labels: v0.2.0, release_note

#108 Add extraction rules examples
  config/crawler.yml.example
  docs/DOCUMENT_SCHEMA.md
  docs/features/EXTRACTION_RULES.md
Labels: v0.2.0

#116 Clean up config docs
  README.md
  config/crawler.yml.example
  config/examples/parks-australia.yml
  docs/CONFIG.md
Labels: v0.2.0

#118 Add schedule command to CLI docs
  docs/CLI.md
Labels: v0.2.0

#114 Misc fixes to the Wolfi-based Dockerfile
  Dockerfile.wolfi
Labels: v0.1.1, v0.2.0, auto-backport

#103 Add docker publishing scripts and pipeline
  .buildkite/publish/build-and-push-multiarch-docker.sh
  .buildkite/publish/build-docker.sh
  .buildkite/publish/publish-common.sh
  .buildkite/publish/push-docker.sh
  .buildkite/publish/test-docker.sh
  .buildkite/release-pipeline.yml
  .buildkite/scripts/run_ci_step.sh
  .buildkite/scripts/run_command.sh
  .gitignore
Labels: v0.1.1, v0.2.0, auto-backport

#121 Add CHANGELOG.md and upgrade to beta
  README.md
  docs/CHANGELOG.md
Labels: v0.2.0, auto-backport

#122 Bump version to 0.3.0
  product_version
Labels: v0.3.0
