Repository elastic/crawler, pull requests merged in 2025-01, with the labels that each got.

#186 Adding check to ES sink to check if index is present before crawling
  lib/crawler/output_sink/elasticsearch.rb
  lib/errors.rb
  spec/lib/crawler/api/crawl_spec.rb
  spec/lib/crawler/coordinator_spec.rb
  spec/lib/crawler/output_sink/elasticsearch_spec.rb
  spec/lib/crawler/output_sink_spec.rb
Labels: v0.2.1

#193 Fixing EXTRACTION_RULES link
  docs/DOCUMENT_SCHEMA.md
Labels: documentation, v0.2.0, auto-backport

#187 [SNYK] Bump nokogiri lib
  Gemfile
  Gemfile.lock
  Jars.lock
Labels: v0.2.2
