Repository elastic/crawler, pull requests merged in 2025-04, with the labels that each got.

#248 Fix Docker permissions issues + Adding optional log volume mount
  Dockerfile
  Dockerfile.wolfi
  docker-compose.yaml
  docs/CLI.md
  docs/CONFIG.md
Labels: v0.2.2

#250 Fallback to xpath to avoid CSS syntax errors
  lib/crawler/data/crawl_result/html.rb
  lib/crawler/data/extraction/rule.rb
  spec/lib/crawler/data/extraction/rule_spec.rb
Labels: v0.3.0

#243 Updated README to include details on setting up logging
  README.md
  docs/features/LOGGING.md
Labels: documentation, v0.3.0, v0.2.2

#252 Make Elasticsearch client compression configurable (default true)
  Jarfile
  Jars.lock
  config/elasticsearch.yml.example
  lib/es/client.rb
  spec/lib/es/client_spec.rb
  vendor/jars/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  vendor/jars/commons-io/commons-io/2.16.1/commons-io-2.16.1.jar
Labels: v0.3.0

#262 New CLI command to test single URLs with a given config
  .gitignore
  lib/crawler/api/config.rb
  lib/crawler/api/crawl.rb
  lib/crawler/cli.rb
  lib/crawler/cli/urltest.rb
  lib/crawler/coordinator.rb
  spec/lib/crawler/api/config_spec.rb
  spec/lib/crawler/api/crawl_spec.rb
  spec/lib/crawler/cli/urltest_spec.rb
  spec/lib/crawler/output_sink/file_spec.rb
Labels: v0.3.0

#265 Updated CLI.md with details about new urltest command
  docs/CLI.md
Labels: v0.3.0

#275 Ensure run_urltest_crawl!() method sets the @crawl_stage instance variable
  lib/crawler/coordinator.rb
Labels: bug, v0.3.0

#279 [Synk] [CVE-2025-32415] Bump Nokogiri to 1.18.8
  Gemfile
  Gemfile.lock
Labels: v0.2.0, auto-backport, v0.2.1, v0.2.2

#284 Improvements to LOGGING.md
  docs/features/LOGGING.md
Labels: v0.3.0

#288 Updating release-pipeline.yml to support building Docker images from main branch
  .buildkite/publish/test-docker.sh
  .buildkite/release-pipeline.yml
Labels: v0.3.0
