Repository elastic/crawler, pull requests merged in 2025-07, with the labels that each got.

#335 Remove RELEASING.md
  docs/RELEASING.md
Labels: v0.4.0

#352 [0.4] Update docker.elastic.co/wolfi/jdk:openjdk-21.35-r1 Docker digest to 56d6979 (#349)
  Dockerfile.wolfi
Labels: backport

#358 Revert the Docker.wolfi base image back to a known working version
  Dockerfile.wolfi
Labels: auto-backport, v0.4.0, v0.3.1

#360 [0.4] Revert the Docker.wolfi base image back to a known working version (#358)
  Dockerfile.wolfi
Labels: backport

#362 [CVE-2024-32002] Pin git version to 2.45.0 in Docker.wolfi
  Dockerfile.wolfi
Labels: auto-backport, v0.4.0, v0.3.1
