Repository elastic/crawler, pull requests merged in 2025-03, with the labels that each got.

#225 Check for build flavor as well as ES version during preflight check
  lib/crawler/output_sink/elasticsearch.rb
  spec/lib/crawler/output_sink/elasticsearch_spec.rb
Labels: auto-backport, v0.2.2

#236 Bump jruby to 9.4.12.0
  .bundler-version
  .ruby-version
  Dockerfile.wolfi
  Gemfile
  Gemfile.lock
  Makefile
  script/vendor_jars
Labels: v0.3.0

#234 Bump rack to 2.2.13
  Gemfile
  Gemfile.lock
Labels: v0.3.0

#237 Bump nokogiri 1.18.6
  Gemfile
  Gemfile.lock
Labels: v0.3.0

#239 Update protobuf-java to 3.25.5
  Jarfile
  Jars.lock
  vendor/jars/com/google/protobuf/protobuf-java/3.21.5/protobuf-java-3.21.5.jar
  vendor/jars/com/google/protobuf/protobuf-java/3.25.5/protobuf-java-3.25.5.jar
Labels: v0.3.0

#238 Write Event and system logs to log files
  .gitignore
  config/crawler.yml.example
  config/filebeat.yml.example
  lib/crawler/api/config.rb
  lib/crawler/event_generator.rb
  lib/crawler/http_executor.rb
  lib/crawler/logging/handler/base.rb
  lib/crawler/logging/handler/file.rb
  lib/crawler/logging/handler/stdout.rb
  lib/crawler/logging/logger.rb
  lib/statically_tagged_logger.rb
  spec/integration/robots_txt_spec.rb
  spec/lib/crawler/event_generator_spec.rb
  spec/lib/crawler/http_client_spec.rb
  spec/lib/crawler/http_executor_spec.rb
  spec/lib/crawler/logging/crawllogger_spec.rb
Labels: enhancement, v0.2.2
