Repository elastic/crawler, pull requests merged in 2025-02, with the labels that each got.

#196 Fix scheduling documentation
  README.md
  config/crawler.yml.example
Labels: v0.2.0, auto-backport, v0.3.0, v0.2.1

#192 Adding ES verification step + explicit best-effort index creation during ES Sink initialization
  lib/crawler/output_sink/elasticsearch.rb
  lib/errors.rb
  spec/lib/crawler/api/crawl_spec.rb
  spec/lib/crawler/coordinator_spec.rb
  spec/lib/crawler/output_sink/elasticsearch_spec.rb
  spec/lib/crawler/output_sink_spec.rb
Labels: enhancement, v0.2.2

#203 Add ingest pipeline for 9.x
  lib/crawler/output_sink/elasticsearch.rb
  spec/lib/crawler/api/crawl_spec.rb
  spec/lib/crawler/coordinator_spec.rb
  spec/lib/crawler/output_sink/elasticsearch_spec.rb
  spec/lib/crawler/output_sink_spec.rb
Labels: auto-backport, v0.2.1

#204 Allow for full HTML extraction
  config/crawler.yml.example
  lib/crawler/api/config.rb
  lib/crawler/document_mapper.rb
  spec/lib/crawler/document_mapper_spec.rb
Labels: auto-backport, v0.2.1

#209 [0.2] Add ingest pipeline for 9.x (#203)
  lib/crawler/output_sink/elasticsearch.rb
  spec/lib/crawler/api/crawl_spec.rb
  spec/lib/crawler/coordinator_spec.rb
  spec/lib/crawler/output_sink/elasticsearch_spec.rb
  spec/lib/crawler/output_sink_spec.rb
Labels: backport

#190 Bump version to 0.2.2
  product_version
Labels: v0.2.2

#213 Update default docker-compose version
  docker-compose.yaml
Labels: auto-backport, v0.2.2

#215 Update FEATURE_COMPARISON.md
  docs/FEATURE_COMPARISON.md
Labels: auto-backport, v0.3.0, v0.2.2

#214 Add`:latest` tag option to build jobs
  .buildkite/publish/build-and-push-multiarch-docker.sh
  .buildkite/publish/publish-common.sh
  .buildkite/release-pipeline.yml
  README.md
  docker-compose.yaml
  docs/CONFIG.md
Labels: auto-backport, v0.3.0, v0.2.2

#217 [0.2] Add&#x60;:latest&#x60; tag option to build jobs (#214)
  .buildkite/publish/build-and-push-multiarch-docker.sh
  .buildkite/publish/publish-common.sh
  .buildkite/release-pipeline.yml
  README.md
Labels: backport
